### ISSUE TITLE
在 flex 中，在高度不確定的 flex container 中以百分比設置 row-gap 無效

### ISSUE THREAD

**Issue by YUN-RU-TSENG** [YUN-RU-TSENG/yun-ru-tseng.github.io#122]
## 問題：為什麼在 flex 中，在 flex container 中以百分比設置 row-gap 無效
自己切版時，習慣使用 gap 設置 flex item 間的 gutter，在這裏發現以百分比 `%` 設置 `row-gap`（row 之間的 gap，也就是垂直方向的間距）會無效，視覺上垂直方向的 gap 會是 0。

但這是為什麼呢？

```html
<div class="a">
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
	<div class="b">b</div>
</div>
```

```css
.a {
	display: flex;
	flex-wrap: wrap;
	row-gap: 10%;
	column-gap: 10%;
	background-color: green;
}

.b {
	background-color: pink;
}
```

渲染結果：

![截圖 2022-11-27 下午1 12 26](https://user-images.githubusercontent.com/41847720/204120308-4c169242-ac85-46e8-b62e-b3e9a70b1928.png)

## 結果：因為 flex container 高度沒有設置，`row-gap` 無法有一個根據計算百分比 `%` 數值
在這裡我在測試的過程中有發現，只需要在 flex container 中設置高度， `row-gap: 10%` 就會作用：

```css
.a {
	display: flex;
	flex-wrap: wrap;
	row-gap: 10%;
	column-gap: 10%;
	background-color: green;
	height: 300px; // 若是有高度設置，row-gap 10% 可以作用
}
```

![截圖 2022-11-27 下午1 22 25](https://user-images.githubusercontent.com/41847720/204120559-72c35ec0-b393-4d36-a463-e445e05db73c.png)

追查相關文件 [[css-sizing] Make flex % row-gap resolve to 0 when height is indefinite (only flex, not grid) · Issue #5081 · w3c/csswg-drafts](https://github.com/w3c/csswg-drafts/issues/5081) 後我總結原因：最上面未設置 flex container 高度的 `row-gap: 10%` 之所以無效，是因為這時高度是隨內容變動的，`row-gap: 10%` 無法有一個依據去計算值，這時後最簡單的解法就是為 flex container 設置高度，`row-gap: 10%` 就可以有依據去計算了。不過其實這不是最好的解法，首先，我們真的需要在垂直方向上設置以百分比為值得 gap 嗎？若是要實現的是一個 grid system，在垂直方向上設置固定高度的 gap 更為合適。

## 參考資料
- [[css-sizing] Make flex % row-gap resolve to 0 when height is indefinite (only flex, not grid) · Issue #5081 · w3c/csswg-drafts](https://github.com/w3c/csswg-drafts/issues/5081)
